title: Nhi Phan
logo: "/images/logo.png?raw=true" 
description: > 
Business Analyst
  <br><br>
  <a href="mailto:nhi.nt.phan@gmail.com">Email Me</a>
  <br><br>
  <a href="https://www.linkedin.com/in/thaonhiphan/">View My LinkedIn Profile</a>
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
